# Generated by Django 5.2.3 on 2025-06-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_company_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company_id',
            new_name='company',
        ),
    ]
