# Generated by Django 5.2.3 on 2025-06-28 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='company_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='company.company'),
        ),
    ]
