# Generated by Django 5.2.3 on 2025-07-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supply',
            field=models.ManyToManyField(blank=True, related_name='supply', to='supply.supply'),
        ),
    ]
