# Generated by Django 5.2.3 on 2025-07-10 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_supply'),
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.supply')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='supply',
            field=models.ManyToManyField(blank=True, related_name='supply', through='product.SupplyProduct', to='supply.supply'),
        ),
    ]
