# Generated by Django 5.2.3 on 2025-07-13 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_supplyproduct'),
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplyes', to='product.product'),
        ),
        migrations.AlterField(
            model_name='supplyproduct',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='supply.supply'),
        ),
    ]
